version: '3.6'
services:
  app:
    build:
      context: ./revys
    depends_on:
      - mongo
    environment: 
      - MONGO_HOST=mongo
    ports:
      - 27017
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data
volumes:
  mongo_data:
